version: '3.9'

services:

  carriercargo_in:
    image: 'bitnami/apache:latest'
    container_name: staticweb-carriercargo-in
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - ./carriercargo.in/public-html:/app
    networks:
      - staticweb
      
  calibrecarriers_com:
    image: 'bitnami/apache:latest'
    container_name: staticweb-calibrecarriers-com
    restart: unless-stopped
    ports:
      - 8082:8080
    volumes:
      - ./calibrecarriers.com/public-html:/app
    networks:
      - staticweb
      
  carriercargo_in_quasar:
    build:
      context: ./quasarweb
      dockerfile: Dockerfile
    image: quasarweb-carriercargo-in
    container_name: quasarweb-carriercargo-in
    restart: unless-stopped
    ports:
      - 8083:8083
    working_dir: /home/node/app
    command: /bin/bash
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
    volumes:
      - ./quasarweb:/home/node/app
    networks:
      - staticweb
      
networks:
  staticweb:
    driver: bridge
